// Hard Skills Types
export type HardSkillCategory =
  | "Fullstack"
  | "Frontend"
  | "Backend"
  | "QA"
  | "DevOps"
  | "Product Manager"
  | "React JS"
  | "Vue"
  | "CSS"
  | "Design Systems"
  | "Nodejs"
  | "Express"
  | "Auth"
  | "Cypress"
  | "Selenium"
  | "Postman"
  | "Docker"
  | "CI_CD"
  | "Kubernetes"
  | "Agile"
  | "Scrum";

// Flattened Hard Skills - direct union of all skill strings
export type HardSkill =
  | "React.js"
  | "Node.js"
  | "MongoDB"
  | "Express"
  | "TypeScript"
  | "React"
  | "Vue"
  | "CSS"
  | "HTML"
  | "Tailwind"
  | "Design Systems"
  | "PostgreSQL"
  | "Redis"
  | "Auth"
  | "Manual Testing"
  | "Cypress"
  | "Selenium"
  | "Postman"
  | "Test Planning"
  | "Docker"
  | "CI/CD"
  | "Kubernetes"
  | "Monitoring"
  | "AWS"
  | "Agile"
  | "Scrum"
  | "Roadmapping"
  | "User Stories"
  | "Prioritization"
  | "Hooks"
  | "Redux"
  | "Next.js"
  | "Testing Library"
  | "Vuex"
  | "Pinia"
  | "Nuxt"
  | "Flexbox"
  | "Grid"
  | "Animations"
  | "Storybook"
  | "Chakra UI"
  | "Material UI"
  | "NestJS"
  | "Socket.io"
  | "Middlewares"
  | "Validation"
  | "Routing"
  | "JWT"
  | "OAuth"
  | "Session Management"
  | "Test Automation"
  | "UI Testing"
  | "Component Testing"
  | "WebDriver"
  | "Cross-browser Testing"
  | "API Testing"
  | "Collections"
  | "Environments"
  | "Docker Compose"
  | "Dockerfile"
  | "Image Optimization"
  | "GitHub Actions"
  | "GitLab CI"
  | "Bitbucket Pipelines"
  | "Helm"
  | "Services"
  | "Clusters"
  | "Sprints"
  | "Kanban"
  | "Retrospectives"
  | "Scrum Master"
  | "Daily Standups"
  | "Backlog Grooming";

