export const SOFT_SKILLS_HIERARCHY = {
  communication: {
    skills: ["Written", "Verbal", "Feedback"],
    color: "cyan",
  },
  collaboration: {
    skills: ["Teamwork", "Pair Programming", "Knowledge Sharing"],
    color: "teal",
  },
  leadership: {
    skills: ["Decision Making", "Mentoring", "Vision Sharing"],
    color: "yellow",
  },
  adaptability: {
    skills: ["Change Management", "Learning", "Resilience"],
    color: "pink",
  },
  problemsolving: {
    skills: ["Root Cause Analysis", "Debugging", "Design Thinking"],
    color: "blue",
  },
} as const;

export const HARD_SKILLS_HIERARCHY = {
  // Main Development Categories
  frontend: {
    skills: [
      // Core Frontend
      "React",
      "Vue",
      "CSS",
      "HTML",
      "Tailwind",
      "Design Systems",
      "TypeScript",
      // React specific
      "Redux",
      "Next.js",
      // Vue specific
      "Vuex",
      "Pinia",
      "Nuxt",
      // Design Systems
      "Storybook",
      "Chakra UI",
      "Material UI",
    ],
    color: "cyan",
  },
  backend: {
    skills: [
      // Core Backend
      "Node.js",
      "Express",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "Auth",
      "TypeScript",
      // Node.js specific
      "NestJS",
      "Socket.io",
      // Auth specific
      "JWT",
      "OAuth",
    ],
    color: "green",
  },
  qa: {
    skills: [
      "Manual Testing",
      "Cypress",
      "Selenium",
      "Postman",
      "Test Planning",
      "Test Automation",
      "UI Testing",
      "Component Testing",
      "WebDriver",
      "Cross-browser Testing",
      "API Testing",
      "Collections",
      "Environments",
    ],
    color: "orange",
  },
  devops: {
    skills: [
      "Docker",
      "CI/CD",
      "Kubernetes",
      "Monitoring",
      "AWS",
      "Docker Compose",
      "Dockerfile",
      "Image Optimization",
      "GitHub Actions",
      "GitLab CI",
      "Bitbucket Pipelines",
      "Helm",
      "Services",
      "Clusters",
    ],
    color: "blue",
  },
  "product manager": {
    skills: [
      "Agile",
      "Scrum",
      "Roadmapping",
      "User Stories",
      "Prioritization",
      "Sprints",
      "Kanban",
      "Retrospectives",
      "Scrum Master",
      "Daily Standups",
      "Backlog Grooming",
    ],
    color: "yellow",
  },
  // Cybersecurity and Cloud Categories
  "blue team": {
    skills: [
      "Splunk",
      "QRadar",
      "LogRhythm",
      "CrowdStrike",
      "SentinelOne",
      "Microsoft Defender",
      "Cortex XSOAR",
      "Splunk SOAR",
      "Palo Alto",
      "FortiGate",
      "Cisco ASA",
      "Snort",
      "Suricata",
      "Cloudflare",
      "AWS WAF",
      "Wireshark",
      "tcpdump",
      "Active Directory",
      "Okta",
      "Duo",
      "McAfee",
      "Symantec",
      "Nessus",
      "Qualys",
      "OpenVAS",
    ],
    color: "blue",
  },
  "red team": {
    skills: [
      "Burp Suite",
      "OWASP ZAP",
      "Metasploit",
      "Nmap",
      "Nikto",
      "SQLmap",
      "Kali Linux",
      "Parrot OS",
      "Hashcat",
      "John the Ripper",
      "Hack The Box",
      "TryHackMe",
    ],
    color: "red",
  },
  "cloud security": {
    skills: [
      "AWS",
      "Azure",
      "GCP",
      "GuardDuty",
      "Azure Sentinel",
      "Prisma Cloud",
      "Docker",
      "Kubernetes",
      "Falco",
      "Aqua Security",
      "Terraform",
      "Ansible",
      "Jenkins",
      "GitHub Actions",
      "Vault",
      "AWS Secrets Manager",
    ],
    color: "purple",
  },
  "scripting & automation": {
    skills: ["Python", "Bash", "PowerShell"],
    color: "green",
  },
  "application security": {
    skills: ["Snyk", "SonarQube", "Checkmarx", "Postman", "Git", "GitHub"],
    color: "orange",
  },
} as const;
