name: CI/CD - Development

on:
  push:
    branches:
      - dev-clean
  pull_request:
    branches:
      - dev-clean
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dev-pipeline:
    uses: ./.github/workflows/shared.yml
    with:
      environment: development
      run_unit_test: false
      run_smoke_test: false
      run_e2e: false
      deploy: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
  create-pr-to-staging:
    needs: dev-pipeline
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Pull Request from dev to staging
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
           gh auth login --with-token <<< "${GITHUB_TOKEN}"
           gh auth setup-git
           if ! gh pr list --base staging --head dev-clean | grep 'Sync dev to staging'; then
             gh pr create --title "Sync dev to staging" --body "Automated PR from dev to staging branch" --base staging --head dev-clean
           else
             echo "PR already exists"
           fi

