name: CI/CD - Development

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-pipeline:
    uses: ./.github/workflows/shared.yml
    with:
      environment: development
      run_smoke_test: false
      run_e2e: false
      deploy: true

  create-pr-to-staging:
    needs: dev-pipeline
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2

      - name: Create Pull Request from dev to staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create --title "Sync dev to staging" --body "Automated PR from dev to staging branch" --base staging --head dev || echo "PR might already exist"

