name: CI/CD - Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      approval_comment:
        description: 'Approval comment (required for manual deployment)'
        required: true
        type: string

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.check.outputs.approved }}
    steps:
      - name: Check for proper approvals
        id: check
        if: github.event_name == 'workflow_dispatch'
        run: |
          # ניתן להוסיף כאן בדיקות מורכבות, לדוגמה בדיקה אם PR מסוים אושר וכו'
          echo "approved=true" >> $GITHUB_OUTPUT

  production-pipeline:
    needs: check-approvals
    if: ${{ github.event_name != 'workflow_dispatch' || needs.check-approvals.outputs.approved == 'true' }}
    uses: ./.github/workflows/shared.yml
    with:
      environment: production
      run_smoke_test: true
      run_e2e: true
      deploy: true

