# .github/workflows/security-checks.yml
name: Security Checks

on:
  # Run security checks on schedule and for pull requests
  schedule:
    # Run weekly on Sunday at 1AM
    - cron: '0 1 * * 0'
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Security Audit
        run: npm audit --audit-level=high
        working-directory: ./client
        continue-on-error: true

      # Optional - Can be enabled later when adding secret scanning
      # - name: Secret Detection
      #   uses: gitleaks/gitleaks-action@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # SonarCloud section - commented out for now
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args: >
      #       -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
      #       -Dsonar.organization=${{ github.repository_owner }}
      #       -Dsonar.sources=./client/src
      #       -Dsonar.tests=./client/src/__tests__
      #       -Dsonar.javascript.lcov.reportPaths=./client/coverage/lcov.info

      - name: Check Dockerfile Security
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: './client/Dockerfile'
          failure-threshold: error
